on:
    push:
    release:

env:
    DOCKER_TAG: ghcr.io/${{ github.repository }}
    VERSION: ${{ github.event_name == 'release' && github.ref_name || format('{0}-{1}', github.ref_name, github.run_number) }}

jobs:
    build:
        runs-on: buildjet-2vcpu-ubuntu-2204-arm
        steps:
        - uses: actions/checkout@v3
        - name: build
          run: docker build -t $DOCKER_TAG:$VERSION .
    upload:
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        steps:
        - name: push docker
          run: echo todo
        - name: upload module
          run: echo todo
