on:
  push:
  release:
    types: [released]

env:
  DOCKER_TAG: ghcr.io/${{ github.repository }}
  VERSION: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}

jobs:
  container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        tags: ${{ env.DOCKER_TAG }}:${{ env.VERSION }}
        pull: true
        platforms: linux/${{ matrix.platform }}
        push: ${{ github.event_name == 'release' }}
    - name: build
      run: |
        TAG=$DOCKER_TAG:$VERSION make module.tar.gz
    - uses: viamrobotics/upload-module@main
      if: github.event_name == 'release'
      with:
        module-path: module.tar.gz
        platform: linux/${{ matrix.platform }}
        version: ${{ env.VERSION }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
