on:
    push:
    release:

env:
    VERSION: ${{ github.event_name == 'release' && github.ref_name || format('{0}-{1}', github.ref_name, github.ref) }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: build
          run: docker build -t $VERSION --platform linux/arm64 .
    upload:
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        steps:
        - name: push docker
          run: echo todo
        - name: upload module
          run: echo todo
